#!/usr/bin/env node
// Renders tools.json into STATIC catalog markup inside index.html, between the
// CATALOG-START/END markers. The hub used to build every card client-side after
// fetching tools.json, which left zero crawlable <a href> in the HTML: Google had
// no path to any tool and none of them were ever indexed. The cards are now in the
// file; the page script only indexes that DOM for search.
//
// Re-run after any tools.json change: node scripts/render-catalog.mjs
// (idempotent - it replaces whatever sits between the markers)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = join(ROOT, 'index.html');
const START = '<!-- CATALOG-START (generated by scripts/render-catalog.mjs - do not edit by hand) -->';
const END = '<!-- CATALOG-END -->';

const CATEGORIES = [
  { id: 'text', label: 'Text &amp; Data' },
  { id: 'design', label: 'Color &amp; Design' },
  { id: 'media', label: 'Image &amp; Media' },
  { id: 'security', label: 'Security &amp; Privacy' },
  { id: 'time', label: 'Time &amp; Date' },
];

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const tools = JSON.parse(readFileSync(join(ROOT, 'tools.json'), 'utf8'));
let html = readFileSync(INDEX, 'utf8');

// Pull the icon SVGs straight out of the page's own <template> elements, so the
// static cards and the templates can never drift apart.
const icons = {};
for (const m of html.matchAll(/<template id="icon-([a-z]+)">([\s\S]*?)<\/template>/g)) icons[m[1]] = m[2].trim();
const missing = [...new Set(tools.map((t) => t.icon))].filter((i) => !icons[i]);
if (missing.length) throw new Error('tools.json uses icons with no <template>: ' + missing.join(', '));
if (!icons.cta) throw new Error('no icon-cta template');

const parts = [];
let index = 0;
for (const cat of CATEGORIES) {
  const inCat = tools.filter((t) => t.category === cat.id);
  if (!inCat.length) continue;
  index += 1;
  const cards = inCat.map((t) => {
    // Same-site relative link: crawlable, and it keeps the tools one click from the hub.
    const href = new URL(t.url).pathname;
    return `                    <a href="${esc(href)}" class="crusher-tool-card hub-card">
                        <span class="hub-card-icon">${icons[t.icon]}</span>
                        <h3 class="hub-card-title">${esc(t.name)}</h3>
                        <p class="hub-card-desc">${esc(t.description)}</p>
                        <span class="hub-card-cta"><span>Launch Tool</span>${icons.cta}</span>
                    </a>`;
  }).join('\n');
  parts.push(`            <section class="hub-section" data-category="${cat.id}">
                <div class="hub-section-header">
                    <span class="hub-section-index">${String(index).padStart(2, '0')}</span>
                    <h2 class="hub-section-title">${cat.label}</h2>
                    <span class="hub-section-count">${inCat.length} tool${inCat.length === 1 ? '' : 's'}</span>
                </div>
                <div class="hub-grid">
${cards}
                </div>
            </section>`);
}

const block = START + '\n' + parts.join('\n') + '\n            ' + END;

if (html.includes(START)) {
  html = html.replace(new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END), block);
} else {
  const empty = '<div id="hub-sections" class="hub-sections"></div>';
  if (!html.includes(empty)) throw new Error('cannot find the #hub-sections container to seed');
  html = html.replace(empty, '<div id="hub-sections" class="hub-sections">\n            ' + block + '\n        </div>');
}

writeFileSync(INDEX, html);
const cardCount = (block.match(/class="crusher-tool-card hub-card"/g) || []).length;
console.log(`[render-catalog] ${cardCount} static tool links across ${parts.length} sections written into index.html`);
